<p><strong>Lessons Learned During the pilot project, a number of key lessons learned were captured by WLC:</strong></p>
<ol>
<li>The need to analyse at the outset, the structure and content of existing invoices as well as the internal invoice matching process prior to creating the validation rules and exception management workflow.</li>
<li>As some suppliers issue credit notes in a different format to their standard invoice, it is important to obtain examples of credit notes prior to go-live to ensure that the conversion to XML can be performed.</li>
<li>The testing phase is a key part of the supplier on-boarding process as it must be ensured that suppliers provide PDF invoices in an HMRC compliant format which also satisfies the validation rules configured.</li>
<li>As purchase order item numbers are fundamental to the matching process for eInvoices, it&rsquo;s important that requisitioners are aware of their responsibilities to raise orders with item numbers that comply with those used in the generation of invoices by suppliers and vice versa. Suppliers also need to ensure that their eInvoices contain item numbers that represent the item numbers displayed on their catalogues and websites.</li>
<li>To ensure that the full benefits of eInvoicing are achieved, requisitioners must assign suitable quantities and unit prices when raising purchase orders. If orders are raised with lines that do not reflect the structure of supplier invoices, there will be a discrepancy when it comes to the matching process thus leading to the need for manual intervention before an invoice can be paid.</li>
<li>Where item numbers are not appropriate, e.g. the supply of a service, it&rsquo;s important that suppliers include the appropriate line number from the purchase order on the invoice. Line numbers can be used as an alternative to item numbers as the validation rules can be configured to match invoice lines to order lines based on the line number.</li>
<li>Requisitioners need to be reminded of the importance of receipting purchase orders to ensure that invoices received electronically will successfully meet the 3-way matching criteria and be passed for payment.</li>
<li>Staff who are responsible for invoicing need to be communicated with to ensure they are aware of the process to follow when a supplier&rsquo;s delivery note acts as an invoice. This is important as there is the possibility for duplicate payments where the eInvoice has been imported with a different invoice number than the delivery note number.</li>
<li>Any eInvoices that fail the 3-way match workflow in PECOS still require manual intervention to resolve.</li>
<li>There is a need to work closely with the procurement team to ensure suppliers are engaged with and educated on an on-going basis as to the benefits that can be realised through eInvoicing.</li>
<li>The procurement team are also key to ensure that catalogues and punch-out sites are accurate and upto-date to minimise the potential of wrong products being ordered or wrong prices appearing on the invoice which would cause mismatches.</li>
<li>The procrement team need to assist in the wider deployment of eInvoicing by including the necessary requirements as part of both existing and new contracts.</li>
</ol>