<?php

declare(strict_types=1);

namespace App\Invoice\Helpers\StoreCove;

Class StoreCoveArrays {

    /**
     * @see https://codebeautify.org/html-to-json-converter
     *
     * @return array
     */
    public static function store_cove_sender_identifier_array(): array {
        $array = [
            -1 => [
                'Region' => 'Region',
                'Country' => 'Country',
                'Legal' => 'Legal',
                'Tax' => 'Tax',
            ],
            0 => [
                'Region' => 'Americas',
                'Country' => 'US',
                'Legal' => 'DUNS, GLN, LEI',
                'Tax' => 'US:EIN, US:SSN',
            ],
            1 => [
                'Region' => 'Americas',
                'Country' => 'CA',
                'Legal' => 'CA:CBN',
                'Tax' => '',
            ],
            2 => [
                'Region' => 'Americas',
                'Country' => 'MX',
                'Legal' => 'MX:RFC',
                'Tax' => '',
            ],
            3 => [
                'Region' => 'AUNZ',
                'Country' => 'AU',
                'Legal' => 'AU:ABN',
                'Tax' => '',
            ],
            4 => [
                'Region' => 'AUNZ',
                'Country' => 'NZ',
                'Legal' => 'GLN',
                'Tax' => 'NZ:GST',
            ],
            5 => [
                'Region' => 'CN',
                'Country' => 'CN',
                'Legal' => 'GLN',
                'Tax' => '',
            ],
            6 => [
                'Region' => 'EEA',
                'Country' => 'CH',
                'Legal' => 'CH:UIDB',
                'Tax' => 'CH:VAT',
            ],
            7 => [
                'Region' => 'EEA',
                'Country' => 'IS',
                'Legal' => 'IS:KTNR',
                'Tax' => 'IS:VAT',
            ],
            8 => [
                'Region' => 'EEA',
                'Country' => 'LI',
                'Legal' => '',
                'Tax' => 'LI:VAT',
            ],
            9 => [
                'Region' => 'EEA',
                'Country' => 'NO',
                'Legal' => 'NO:ORG',
                'Tax' => 'NO:VAT',
            ],
            10 => [
                'Region' => 'EU',
                'Country' => 'AD',
                'Legal' => '',
                'Tax' => 'AD:VAT',
            ],
            11 => [
                'Region' => 'EU',
                'Country' => 'AL',
                'Legal' => '',
                'Tax' => 'AL:VAT',
            ],
            12 => [
                'Region' => 'EU',
                'Country' => 'AT',
                'Legal' => '',
                'Tax' => 'AT:VAT',
            ],
            13 => [
                'Region' => 'EU',
                'Country' => 'BA',
                'Legal' => '',
                'Tax' => 'BA:VAT',
            ],
            14 => [
                'Region' => 'EU',
                'Country' => 'BE',
                'Legal' => 'BE:EN',
                'Tax' => 'BE:VAT',
            ],
            15 => [
                'Region' => 'EU',
                'Country' => 'BG',
                'Legal' => '',
                'Tax' => 'BG:VAT',
            ],
            16 => [
                'Region' => 'EU',
                'Country' => 'CY',
                'Legal' => '',
                'Tax' => 'CY:VAT',
            ],
            17 => [
                'Region' => 'EU',
                'Country' => 'CZ',
                'Legal' => '',
                'Tax' => 'CZ:VAT',
            ],
            18 => [
                'Region' => 'EU',
                'Country' => 'DE',
                'Legal' => 'DE:LWID',
                'Tax' => '',
            ],
            19 => [
                'Region' => 'EU',
                'Country' => 'DE',
                'Legal' => '',
                'Tax' => 'DE:VAT',
            ],
            20 => [
                'Region' => 'EU',
                'Country' => 'DK',
                'Legal' => 'DK:DIGST',
                'Tax' => 'DK:ERST',
            ],
            21 => [
                'Region' => 'EU',
                'Country' => 'EE',
                'Legal' => 'EE:CC',
                'Tax' => 'EE:VAT',
            ],
            22 => [
                'Region' => 'EU',
                'Country' => 'ES',
                'Legal' => '',
                'Tax' => 'ES:VAT',
            ],
            23 => [
                'Region' => 'EU',
                'Country' => 'FI',
                'Legal' => 'FI:ORG',
                'Tax' => 'FI:VAT',
            ],
            24 => [
                'Region' => 'EU',
                'Country' => 'FR',
                'Legal' => 'FR:SIRENE or FR:SIRET',
                'Tax' => 'FR:VAT',
            ],
            25 => [
                'Region' => 'EU',
                'Country' => 'GR',
                'Legal' => '',
                'Tax' => 'GR:VAT',
            ],
            26 => [
                'Region' => 'EU',
                'Country' => 'HR',
                'Legal' => '',
                'Tax' => 'HR:VAT',
            ],
            27 => [
                'Region' => 'EU',
                'Country' => 'HU',
                'Legal' => '',
                'Tax' => 'HU:VAT',
            ],
            28 => [
                'Region' => 'EU',
                'Country' => 'IE',
                'Legal' => '',
                'Tax' => 'IE:VAT',
            ],
            29 => [
                'Region' => 'EU',
                'Country' => 'IT',
                'Legal' => '',
                'Tax' => 'IT:IVA',
            ],
            30 => [
                'Region' => 'EU',
                'Country' => 'IT',
                'Legal' => '',
                'Tax' => 'IT:CF and/or IT:IVA',
            ],
            31 => [
                'Region' => 'EU',
                'Country' => 'IT',
                'Legal' => '',
                'Tax' => 'IT:CF',
            ],
            32 => [
                'Region' => 'EU',
                'Country' => 'IT',
                'Legal' => '',
                'Tax' => 'IT:IVA',
            ],
            33 => [
                'Region' => 'EU',
                'Country' => 'LT',
                'Legal' => 'LT:LEC',
                'Tax' => 'LT:VAT',
            ],
            34 => [
                'Region' => 'EU',
                'Country' => 'LU',
                'Legal' => 'LU:MAT (Matricule PM; optional)',
                'Tax' => 'LU:VAT',
            ],
            35 => [
                'Region' => 'EU',
                'Country' => 'LV',
                'Legal' => '',
                'Tax' => 'LV:VAT',
            ],
            36 => [
                'Region' => 'EU',
                'Country' => 'MC',
                'Legal' => '',
                'Tax' => 'MC:VAT',
            ],
            37 => [
                'Region' => 'EU',
                'Country' => 'ME',
                'Legal' => '',
                'Tax' => 'ME:VAT',
            ],
            38 => [
                'Region' => 'EU',
                'Country' => 'MK',
                'Legal' => '',
                'Tax' => 'MK:VAT',
            ],
            39 => [
                'Region' => 'EU',
                'Country' => 'MT',
                'Legal' => '',
                'Tax' => 'MT:VAT',
            ],
            40 => [
                'Region' => 'EU',
                'Country' => 'NL',
                'Legal' => 'NL:KVK',
                'Tax' => 'NL:VAT',
            ],
            41 => [
                'Region' => 'EU',
                'Country' => 'PL',
                'Legal' => '',
                'Tax' => 'PL:VAT',
            ],
            42 => [
                'Region' => 'EU',
                'Country' => 'PT',
                'Legal' => '',
                'Tax' => 'PT:VAT',
            ],
            43 => [
                'Region' => 'EU',
                'Country' => 'RO',
                'Legal' => '',
                'Tax' => 'RO:VAT',
            ],
            44 => [
                'Region' => 'EU',
                'Country' => 'RS',
                'Legal' => '',
                'Tax' => 'RS:VAT',
            ],
            45 => [
                'Region' => 'EU',
                'Country' => 'SE',
                'Legal' => 'SE:ORGNR',
                'Tax' => 'SE:VAT',
            ],
            46 => [
                'Region' => 'EU',
                'Country' => 'SI',
                'Legal' => '',
                'Tax' => 'SI:VAT',
            ],
            47 => [
                'Region' => 'EU',
                'Country' => 'SK',
                'Legal' => '',
                'Tax' => 'SK:VAT',
            ],
            48 => [
                'Region' => 'EU',
                'Country' => 'SM',
                'Legal' => '',
                'Tax' => 'SM:VAT',
            ],
            49 => [
                'Region' => 'EU',
                'Country' => 'TR',
                'Legal' => '',
                'Tax' => 'TR:VAT',
            ],
            50 => [
                'Region' => 'EU',
                'Country' => 'VA',
                'Legal' => '',
                'Tax' => 'VA:VAT',
            ],
            51 => [
                'Region' => 'IN',
                'Country' => 'IN',
                'Legal' => '',
                'Tax' => 'IN:GSTIN',
            ],
            52 => [
                'Region' => 'JP',
                'Country' => 'JP',
                'Legal' => 'JP:SST (alias: JP:LIN, use is discouraged)',
                'Tax' => 'JP:IIN (deprecated: JP:TIN)',
            ],
            53 => [
                'Region' => 'SG',
                'Country' => 'SG',
                'Legal' => 'SG:UEN',
                'Tax' => 'SG:GST (optional)',
            ],
            54 => [
                'Region' => 'World',
                'Country' => 'GB',
                'Legal' => '',
                'Tax' => 'GB:VAT',
            ],
            55 => [
                'Region' => 'World',
                'Country' => 'SA',
                'Legal' => '',
                'Tax' => 'SA:TIN',
            ],
            56 => [
                'Region' => 'World',
                'Country' => 'Other',
                'Legal' => 'DUNS, GLN, LEI',
                'Tax' => '',
            ],
        ];
        return $array;
    }

    /**
     *
     * @return array
     */
    public static function store_cove_receiver_identifier_array(): array {
        $array = [
            -1 => [
                'region' => 'Region',
                'country' => 'Country',
                'b2x' => 'B2X',
                'legal' => 'Legal',
                'tax' => 'Tax',
                'routing' => 'Routing'
            ],
            0 => [
                'region' => 'Americas',
                'country' => 'US',
                'b2x' => 'B',
                'legal' => 'DUNS',
                'tax' => ' GLN',
                'routing' => ' LEI',
            ],
            1 => [
                'region' => 'Americas',
                'country' => 'CA',
                'b2x' => 'B',
                'legal' => 'CA:CBN',
                'tax' => '',
                'routing' => 'CA:CBN',
            ],
            2 => [
                'region' => 'Americas',
                'country' => 'MX',
                'b2x' => 'B',
                'legal' => 'MX:RFC',
                'tax' => '',
                'routing' => 'MX:RFC',
            ],
            3 => [
                'region' => 'AUNZ',
                'country' => 'AU',
                'b2x' => 'B+G',
                'legal' => 'AU:ABN',
                'tax' => '',
                'routing' => 'AU:ABN',
            ],
            4 => [
                'region' => 'AUNZ',
                'country' => 'NZ',
                'b2x' => 'B+G',
                'legal' => 'GLN',
                'tax' => 'NZ:GST',
                'routing' => 'GLN',
            ],
            5 => [
                'region' => 'EEA',
                'country' => 'CH',
                'b2x' => 'B+G',
                'legal' => 'CH:UIDB',
                'tax' => 'CH:VAT',
                'routing' => 'CH:UIDB',
            ],
            6 => [
                'region' => 'EEA',
                'country' => 'IS',
                'b2x' => 'B+G',
                'legal' => 'IS:KTNR',
                'tax' => 'IS:VAT',
                'routing' => 'IS:KTNR',
            ],
            7 => [
                'region' => 'EEA',
                'country' => 'LI',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'LI:VAT',
                'routing' => 'LI:VAT',
            ],
            8 => [
                'region' => 'EEA',
                'country' => 'NO',
                'b2x' => 'B+G',
                'legal' => 'NO:ORG',
                'tax' => 'NO:VAT',
                'routing' => 'NO:ORG',
            ],
            9 => [
                'region' => 'EU',
                'country' => 'AD',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'AD:VAT',
                'routing' => 'AD:VAT',
            ],
            10 => [
                'region' => 'EU',
                'country' => 'AL',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'AL:VAT',
                'routing' => 'AL:VAT',
            ],
            11 => [
                'region' => 'EU',
                'country' => 'AT',
                'b2x' => 'G',
                'legal' => 'AT:GOV',
                'tax' => '',
                'routing' => 'Centralized id: 9915:b',
            ],
            12 => [
                'region' => 'EU',
                'country' => 'AT',
                'b2x' => 'B',
                'legal' => '',
                'tax' => 'AT:VAT',
                'routing' => 'AT:VAT',
            ],
            13 => [
                'region' => 'EU',
                'country' => 'BA',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'BA:VAT',
                'routing' => 'BA:VAT',
            ],
            14 => [
                'region' => 'EU',
                'country' => 'BE',
                'b2x' => 'B+G',
                'legal' => 'BE:EN',
                'tax' => 'BE:VAT',
                'routing' => 'BE:EN',
            ],
            15 => [
                'region' => 'EU',
                'country' => 'BG',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'BG:VAT',
                'routing' => 'BG:VAT',
            ],
            16 => [
                'region' => 'EU',
                'country' => 'CY',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'CY:VAT',
                'routing' => 'CY:VAT',
            ],
            17 => [
                'region' => 'EU',
                'country' => 'CZ',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'CZ:VAT',
                'routing' => 'CZ:VAT',
            ],
            18 => [
                'region' => 'EU',
                'country' => 'DE',
                'b2x' => 'G',
                'legal' => 'DE:LWID',
                'tax' => '',
                'routing' => 'DE:LWID',
            ],
            19 => [
                'region' => 'EU',
                'country' => 'DE',
                'b2x' => 'B',
                'legal' => '',
                'tax' => 'DE:VAT',
                'routing' => 'DE:VAT',
            ],
            20 => [
                'region' => 'EU',
                'country' => 'DK',
                'b2x' => 'B+G',
                'legal' => 'DK:DIGST',
                'tax' => 'DK:ERST',
                'routing' => 'DK:DIGST',
            ],
            21 => [
                'region' => 'EU',
                'country' => 'EE',
                'b2x' => 'B+G',
                'legal' => 'EE:CC',
                'tax' => 'EE:VAT',
                'routing' => 'EE:CC',
            ],
            22 => [
                'region' => 'EU',
                'country' => 'ES',
                'b2x' => 'B',
                'legal' => '',
                'tax' => 'ES:VAT',
                'routing' => 'ES:VAT',
            ],
            23 => [
                'region' => 'EU',
                'country' => 'FI',
                'b2x' => 'B+G',
                'legal' => 'FI:ORG',
                'tax' => 'FI:VAT',
                'routing' => 'FI:OVT',
            ],
            24 => [
                'region' => 'EU',
                'country' => 'FR',
                'b2x' => 'G',
                'legal' => 'FR:SIRET + customerAssignedAccountIdValue',
                'tax' => '',
                'routing' => 'Centralized id: 0009:11000201100044',
            ],
            25 => [
                'region' => 'EU',
                'country' => 'FR',
                'b2x' => 'B',
                'legal' => 'FR:SIRENE or FR:SIRET',
                'tax' => 'FR:VAT',
                'routing' => 'FR:SIRENE or FR:SIRET',
            ],
            26 => [
                'region' => 'EU',
                'country' => 'GR',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'GR:VAT',
                'routing' => 'GR:VAT',
            ],
            27 => [
                'region' => 'EU',
                'country' => 'HR',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'HR:VAT',
                'routing' => 'HR:VAT',
            ],
            28 => [
                'region' => 'EU',
                'country' => 'HU',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'HU:VAT',
                'routing' => 'HU:VAT',
            ],
            29 => [
                'region' => 'EU',
                'country' => 'IE',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'IE:VAT',
                'routing' => 'IE:VAT',
            ],
            30 => [
                'region' => 'EU',
                'country' => 'IT',
                'b2x' => 'G (Peppol)',
                'legal' => '',
                'tax' => 'IT:IVA',
                'routing' => 'IT:CUUO',
            ],
            31 => [
                'region' => 'EU',
                'country' => 'IT',
                'b2x' => 'B (SDI)',
                'legal' => '',
                'tax' => 'IT:CF and/or IT:IVA',
                'routing' => 'IT:CUUO',
            ],
            32 => [
                'region' => 'EU',
                'country' => 'IT',
                'b2x' => 'C (SDI)',
                'legal' => '',
                'tax' => 'IT:CF',
                'routing' => 'Email',
            ],
            33 => [
                'region' => 'EU',
                'country' => 'IT',
                'b2x' => 'G (SDI)',
                'legal' => '',
                'tax' => 'IT:IVA',
                'routing' => 'IT:CUUO',
            ],
            34 => [
                'region' => 'EU',
                'country' => 'LT',
                'b2x' => 'B+G',
                'legal' => 'LT:LEC',
                'tax' => 'LT:VAT',
                'routing' => 'LT:LEC',
            ],
            35 => [
                'region' => 'EU',
                'country' => 'LU',
                'b2x' => 'B+G',
                'legal' => 'LU:MAT (Matricule PM; optional)',
                'tax' => 'LU:VAT',
                'routing' => 'LU:VAT',
            ],
            36 => [
                'region' => 'EU',
                'country' => 'LV',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'LV:VAT',
                'routing' => 'LV:VAT',
            ],
            37 => [
                'region' => 'EU',
                'country' => 'MC',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'MC:VAT',
                'routing' => 'MC:VAT',
            ],
            38 => [
                'region' => 'EU',
                'country' => 'ME',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'ME:VAT',
                'routing' => 'ME:VAT',
            ],
            39 => [
                'region' => 'EU',
                'country' => 'MK',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'MK:VAT',
                'routing' => 'MK:VAT',
            ],
            40 => [
                'region' => 'EU',
                'country' => 'MT',
                'b2x' => 'B+G',
                'legal' => '',
                'tax' => 'MT:VAT',
                'routing' => 'MT:VAT',
            ],
            41 => [
                'region' => 'EU',
                'country' => 'NL',
                'b2x' => 'G',
                'legal' => 'NL:OINO',
                'tax' => '',
                'routing' => 'NL:OINO',
            ],
            42 => [
                'region' => 'EU',
                'country' => 'NL',
                'b2x' => 'B',
                'legal' => 'NL:KVK',
                'tax' => 'NL:VAT',
                'routing' => 'NL:KVK or NL:VAT',
            ],
            43 => [
                'region' => 'EU',
                'country' => 'PL',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'PL:VAT',
                'routing' => 'PL:VAT',
            ],
            44 => [
                'region' => 'EU',
                'country' => 'PT',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'PT:VAT',
                'routing' => 'PT:VAT',
            ],
            45 => [
                'region' => 'EU',
                'country' => 'RO',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'RO:VAT',
                'routing' => 'RO:VAT',
            ],
            46 => [
                'region' => 'EU',
                'country' => 'RS',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'RS:VAT',
                'routing' => 'RS:VAT',
            ],
            47 => [
                'region' => 'EU',
                'country' => 'SE',
                'b2x' => 'G+B',
                'legal' => 'SE:ORGNR',
                'tax' => 'SE:VAT',
                'routing' => 'SE:ORGNR',
            ],
            48 => [
                'region' => 'EU',
                'country' => 'SI',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'SI:VAT',
                'routing' => 'SI:VAT',
            ],
            49 => [
                'region' => 'EU',
                'country' => 'SK',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'SK:VAT',
                'routing' => 'SK:VAT',
            ],
            50 => [
                'region' => 'EU',
                'country' => 'SM',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'SM:VAT',
                'routing' => 'SM:VAT',
            ],
            51 => [
                'region' => 'EU',
                'country' => 'TR',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'TR:VAT',
                'routing' => 'TR:VAT',
            ],
            52 => [
                'region' => 'EU',
                'country' => 'VA',
                'b2x' => 'G+B',
                'legal' => '',
                'tax' => 'VA:VAT',
                'routing' => 'VA:VAT',
            ],
            53 => [
                'region' => 'IN',
                'country' => 'IN',
                'b2x' => 'B',
                'legal' => '',
                'tax' => 'IN:GSTIN',
                'routing' => 'Email',
            ],
            54 => [
                'region' => 'JP',
                'country' => 'JP',
                'b2x' => 'B',
                'legal' => 'JP:SST (alias: JP:LIN',
                'tax' => ' use is discouraged)',
                'routing' => 'JP:IIN (deprecated: JP:TIN)',
            ],
            55 => [
                'region' => 'SG',
                'country' => 'SG',
                'b2x' => 'G',
                'legal' => 'SG:UEN with special requirements',
                'tax' => '',
                'routing' => 'Centralized id: 0195:SGUENT08GA0028A',
            ],
            56 => [
                'region' => 'SG',
                'country' => 'SG',
                'b2x' => 'B',
                'legal' => 'SG:UEN',
                'tax' => 'SG:GST (optional)',
                'routing' => 'SG:UEN',
            ],
            57 => [
                'region' => 'World',
                'country' => 'GB',
                'b2x' => 'B',
                'legal' => '',
                'tax' => 'GB:VAT',
                'routing' => 'GB:VAT',
            ],
            58 => [
                'region' => 'World',
                'country' => 'SA',
                'b2x' => 'B',
                'legal' => '',
                'tax' => 'SA:TIN',
                'routing' => 'Email',
            ],
            59 => [
                'region' => 'World',
                'country' => 'Other',
                'b2x' => 'B',
                'legal' => 'DUNS',
                'tax' => ' GLN',
                'routing' => ' LEI',
            ],
        ];

        return $array;
    }
}
