---
- name: Create folder
  file:
    path: /home/deploy/yii3i.yii3i.co.uk/var/ssl/dhparam
    state: directory
    recurse: true

- name: Generate dhparam
  command: openssl dhparam -out ./var/ssl/dhparam/dhparam-2048.pem 2048
  args:
    chdir: /home/deploy/yii3i.yii3i.co.uk
    creates: ./var/ssl/dhparam/dhparam-2048.pem